[package]
name = "multiplayer"
version = "1.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
thiserror = "2"
base64 = "0.22"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
